### ISSUE TITLE
add paper issue

### ISSUE THREAD

**Issue by sinxuy** [hongleizhang/RSPapers#4]
Deep Interest Network for Click-Through Rate Prediction
Deep Interest Evolution Network for Click-Through Rate Prediction
Operation-aware Neural Networks for User Response Prediction
Feature Generation by Convolutional Neural Network for Click-Through Rate Prediction
Deep Session Interest Network for Click-Through Rate Prediction
Deep Spatio-Temporal Neural Networks for Click-Through Rate Prediction
Practice on Long Sequential User Behavior Modeling for Click-Through Rate Prediction

**Comment by hongleizhang** [comment]
感谢提供论文列表，这部分可以放在ctr for rs上

**Comment by hongleizhang** [comment]
已新增CTR Prediction for RS模块，感谢。
